### PR TITLE
Introduce flake.nix for project to build for NixOS

### PR DESCRIPTION
**Pull request by fzakaria**
Create flake.nix for the project so that we can reproducibly build this project using Nix software and on NixOS machines.

You can also easily run this directly from the repository using the flake.
```console
❯ nix shell github:fzakaria/GlobalProtect-openconnect/add-flake-nix -c gpclient
gpclient 2.3.3 (2024-07-08)
Kevin Yue <k3vinyue@gmail.com>

The GlobalProtect VPN client, based on OpenConnect, supports the SSO authentication method.

Usage: gpclient [OPTIONS] <COMMAND>

Commands:
  connect     Connect to a portal server
  disconnect  Disconnect from the server
  launch-gui  Launch the GUI
  help        Print this message or the help of the given subcommand(s)
```

I spent time trying to see if I can get on my Global Protect VPN + Okta but to no avail.
Publishing this work in case it helps others.

Thanks for the software.

### CODE REVIEW

**Comment by yuezk** [comment]
Hi @fzakaria thanks for your contribution.

> I` spent time trying to see if I can get on my Global Protect VPN + Okta but to no avail.

You could try `sudo -E gpclient connect <portal> --default-browser` to see if it works for you.

**Comment by fzakaria** [comment]
This doesn't run through Make just the rust build of the CLI tools. 

Seems good enough for the CLI 🥲 portion.

**Comment by yuezk** [comment]
I will continue improving the Nix packaging.

> Yea something about Okta they don't like me connecting.
They might whitelist my MAC that I need to spoof ?
(Similar to HIP ?)

Can you provide the logs for this, so I can see which step you have reached?

**Comment by fzakaria** [comment]
We can setup Cachix also for the flake

[example](https://github.com/cachix/cachix/blob/master/flake.nix):
```
  nixConfig = {
    extra-substituters = "https://cachix.cachix.org";
    extra-trusted-public-keys = "cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=";
  };
```

**Comment by ericdallo** [comment]
@fzakaria how did you manage to make it work with CLI only? because for my gateway, it requires opening a browser for okta auth, it opens sucessfully with the --default-browser, but the cli keeps listening even after authorized in the browser

**Comment by ericdallo** [comment]
the browser tries to launch an external handler of `globalprotectcallback` but it doesn't recognize (even manually copying it and doing a xdg-open <handler>
)

**Comment by fzakaria** [comment]
The callback is in the .desktop file but that's only registered for the GUI ever and not the CLI ?
We can add the .desktop to the Nix derivation but that might only help on NixOS.

Do you have a working VPN I can test the flow ?
I never got past the Auth for other reasons

**Comment by ericdallo** [comment]
Not really @fzakaria I'm using a vpn from my work, could you detail about the .desktop and how can we make that handler work? I feel like this is the only missing part

**Comment by ericdallo** [comment]
I created the .desktop file as [here](https://github.com/yuezk/GlobalProtect-openconnect/blob/main/packaging/files/usr/share/applications/gpgui.desktop) and that fixed the problem, but then I faced a new one:
```
[2024-08-16T23:16:01Z INFO  gpclient::cli] gpclient started: 2.3.3 (2024-08-16)
[2024-08-16T23:16:01Z INFO  gpclient::cli] TLS errors will be ignored
[2024-08-16T23:16:01Z INFO  gpapi::portal::prelogin] Portal prelogin with user_agent: PAN GlobalProtect
[2024-08-16T23:16:01Z INFO  gpauth::cli] gpauth started: 2.3.3 (2024-08-16)
[2024-08-16T23:16:01Z INFO  gpauth::cli] TLS errors will be ignored
[2024-08-16T23:16:01Z INFO  gpauth::cli] Please continue the authentication process in the default browser
[2024-08-16T23:16:01Z INFO  gpclient::connect] Waiting for the browser authentication to complete...
[2024-08-16T23:16:01Z INFO  gpclient::connect] Listening authentication data on port 39871
[2024-08-16T23:16:05Z INFO  gpclient::connect] Received the browser authentication data from the socket
[2024-08-16T23:16:05Z INFO  gpapi::auth] Parsing SAML auth data...
[2024-08-16T23:16:05Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect
[2024-08-16T23:16:05Z INFO  gpapi::gateway::parse_gateways] Using external gateways
> Which gateway do you want to connect to? xxx (xxx)
[2024-08-16T23:16:12Z INFO  gpclient::connect] Connecting to the selected gateway: xxx (xxx)
[2024-08-16T23:16:12Z INFO  gpapi::gateway::login] Gateway login, user_agent: PAN GlobalProtect
[2024-08-16T23:16:12Z INFO  gpclient::connect] Failed to connect portal with prelogin: Failed to find vpnc-script

Error: Failed to find vpnc-script
```

**Comment by yuezk** [comment]
@ericdallo The error is about the `vpnc-script`. Did you install it, or did you specify a custom one?

**Comment by ericdallo** [comment]
@yuezk I never heard about it before when using the 1.4.9 version, is there anything mentioning what or where to install it?
I'm using NixOs, trying that flake

**Comment by ericdallo** [comment]
Ok, installed vpnc, but I think we need to patch [these paths](https://github.com/yuezk/GlobalProtect-openconnect/blob/30bec40338aec89223b0a2eb631b02ccfd93a51c/crates/common/src/vpn_utils.rs#L5) for nix

**Comment by ericdallo** [comment]
I fixed [here](https://github.com/yuezk/GlobalProtect-openconnect/pull/413/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R46-R47), it seems to pass and stuck in a next step, I have no idea what is that IPSec gateway address:
```
[2024-08-18T01:55:26Z INFO  gpclient::cli] gpclient started: 2.3.7 (2024-08-18)
[2024-08-18T01:55:26Z INFO  gpclient::cli] TLS errors will be ignored
[2024-08-18T01:55:26Z INFO  gpclient::connect] Treating the server as a gateway
[2024-08-18T01:55:26Z INFO  gpclient::connect] Performing the gateway authentication...
[2024-08-18T01:55:26Z INFO  gpapi::portal::prelogin] Gateway prelogin with user_agent: PAN GlobalProtect
[2024-08-18T01:55:26Z INFO  gpapi::portal::prelogin] Perform prelogin, user_agent: PAN GlobalProtect
[2024-08-18T01:55:26Z INFO  gpauth::cli] gpauth started: 2.3.7 (2024-08-18)
[2024-08-18T01:55:26Z INFO  gpauth::cli] TLS errors will be ignored
[2024-08-18T01:55:26Z INFO  gpapi::process::browser_authenticator] Launching the default browser...
[2024-08-18T01:55:26Z INFO  gpauth::cli] Please continue the authentication process in the default browser
[2024-08-18T01:55:26Z INFO  gpauth::cli] Listening authentication data on port 35459
[2024-08-18T01:55:26Z INFO  gpauth::cli] If it hangs, please check the logs at `/tmp/gpcallback.log` for more information
[2024-08-18T01:55:31Z INFO  gpauth::cli] Received the browser authentication data from the socket
[2024-08-18T01:55:31Z INFO  gpauth::cli] Authentication completed
[2024-08-18T01:55:31Z INFO  gpapi::gateway::login] Perform gateway login, user_agent: PAN GlobalProtect
[2024-08-18T01:55:31Z INFO  openconnect::ffi] openconnect version: v9.12
[2024-08-18T01:55:31Z INFO  openconnect::ffi] User agent: PAN GlobalProtect
[2024-08-18T01:55:31Z INFO  openconnect::ffi] VPNC script: /nix/store/yv40aa3rlj1x0q2zl6j1wdl98zm1611r-vpnc-unstable-2021-11-04/bin/vpnc
[2024-08-18T01:55:31Z INFO  openconnect::ffi] OS: linux
[2024-08-18T01:55:31Z INFO  openconnect::ffi] CSD_USER: 1000
[2024-08-18T01:55:31Z INFO  openconnect::ffi] CSD_WRAPPER: (null)
[2024-08-18T01:55:31Z INFO  openconnect::ffi] RECONNECT_TIMEOUT: 300
[2024-08-18T01:55:31Z INFO  openconnect::ffi] MTU: 0
[2024-08-18T01:55:31Z INFO  openconnect::ffi] DISABLE_IPV6: 0
[2024-08-18T01:55:31Z INFO  openconnect::ffi] NO_DTLS: 0
[2024-08-18T01:55:31Z INFO  openconnect::ffi] POST https://xxx/ssl-vpn/getconfig.esp
[2024-08-18T01:55:31Z INFO  openconnect::ffi] Connected to xxx
[2024-08-18T01:55:31Z INFO  openconnect::ffi] SSL negotiation with xxx
[2024-08-18T01:55:31Z INFO  openconnect::ffi] Connected to HTTPS on xxx with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
[2024-08-18T01:55:31Z INFO  openconnect::ffi] Tunnel timeout (rekey interval) is 180 minutes.
[2024-08-18T01:55:31Z INFO  openconnect::ffi] Idle timeout is 180 minutes.
[2024-08-18T01:55:31Z WARN  openconnect::ffi] No MTU received. Calculated 1422 for ESP tunnel
[2024-08-18T01:55:31Z INFO  openconnect::ffi] POST https://xxx/ssl-vpn/hipreportcheck.esp
[2024-08-18T01:55:31Z WARN  openconnect::ffi] WARNING: Server asked us to submit HIP report with md5sum xxx.
        VPN connectivity may be disabled or limited without HIP report submission.
        You need to provide a --csd-wrapper argument with the HIP report submission script.
[2024-08-18T01:55:31Z INFO  openconnect::ffi] ESP session established with server
[2024-08-18T01:55:31Z INFO  openconnect::ffi] ESP tunnel connected; exiting HTTPS mainloop.
Enter IPSec gateway address: 
```

**Comment by yuezk** [comment]
@ericdallo The "Enter IPSec gateway address" error may related to the vpnc script you use. Looks like you specified the `vpnc` executable instead of the vpnc script.

You need to install the vpnc-script, see https://www.infradead.org/openconnect/vpnc-script.html

**Comment by ericdallo** [comment]
Sorry for my ignorance @yuezk, After understanding it's a different thing, I realized nix already had a package for vpnc-script and using that fix not only the problem but made the vpn work finally!

I opened a PR fixing it in your flake, LMK what you think: https://github.com/yuezk/GlobalProtect-openconnect/pull/413
I'll try to make the desktop file work in the flake as well since right now I created one only for my config, if so I will open a next PR

output
```
2024-08-18T11:56:51Z INFO  gpclient::cli] gpclient started: 2.3.7 (2024-08-18)
[2024-08-18T11:56:51Z INFO  gpclient::cli] TLS errors will be ignored
[2024-08-18T11:56:51Z INFO  gpclient::connect] Treating the server as a gateway
[2024-08-18T11:56:51Z INFO  gpclient::connect] Performing the gateway authentication...
[2024-08-18T11:56:51Z INFO  gpapi::portal::prelogin] Gateway prelogin with user_agent: PAN GlobalProtect
[2024-08-18T11:56:51Z INFO  gpapi::portal::prelogin] Perform prelogin, user_agent: PAN GlobalProtect
[2024-08-18T11:56:51Z INFO  gpauth::cli] gpauth started: 2.3.7 (2024-08-18)
[2024-08-18T11:56:51Z INFO  gpauth::cli] TLS errors will be ignored
[2024-08-18T11:56:51Z INFO  gpapi::process::browser_authenticator] Launching the default browser...
[2024-08-18T11:56:51Z INFO  gpauth::cli] Please continue the authentication process in the default browser
[2024-08-18T11:56:51Z INFO  gpauth::cli] Listening authentication data on port 40217
[2024-08-18T11:56:51Z INFO  gpauth::cli] If it hangs, please check the logs at `/tmp/gpcallback.log` for more information
[2024-08-18T11:56:57Z INFO  gpauth::cli] Received the browser authentication data from the socket
[2024-08-18T11:56:57Z INFO  gpauth::cli] Authentication completed
[2024-08-18T11:56:57Z INFO  gpapi::gateway::login] Perform gateway login, user_agent: PAN GlobalProtect
[2024-08-18T11:56:57Z INFO  openconnect::ffi] openconnect version: v9.12
[2024-08-18T11:56:57Z INFO  openconnect::ffi] User agent: PAN GlobalProtect
[2024-08-18T11:56:57Z INFO  openconnect::ffi] VPNC script: /nix/store/0ssrnsbzwa57vvhsi5kmmnp5qs8a3hxz-vpnc-scripts-unstable-2023-01-03/bin/vpnc-script
[2024-08-18T11:56:57Z INFO  openconnect::ffi] OS: linux
[2024-08-18T11:56:57Z INFO  openconnect::ffi] CSD_USER: 1000
[2024-08-18T11:56:57Z INFO  openconnect::ffi] CSD_WRAPPER: (null)
[2024-08-18T11:56:57Z INFO  openconnect::ffi] RECONNECT_TIMEOUT: 300
[2024-08-18T11:56:57Z INFO  openconnect::ffi] MTU: 0
[2024-08-18T11:56:57Z INFO  openconnect::ffi] DISABLE_IPV6: 0
[2024-08-18T11:56:57Z INFO  openconnect::ffi] NO_DTLS: 0
[2024-08-18T11:56:57Z INFO  openconnect::ffi] POST https://xxx/ssl-vpn/getconfig.esp
[2024-08-18T11:56:57Z INFO  openconnect::ffi] Connected to 190.111.189.251:443
[2024-08-18T11:56:57Z INFO  openconnect::ffi] SSL negotiation with xxx
[2024-08-18T11:56:57Z INFO  openconnect::ffi] Connected to HTTPS on xxx with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
[2024-08-18T11:56:57Z INFO  openconnect::ffi] Tunnel timeout (rekey interval) is 180 minutes.
[2024-08-18T11:56:57Z INFO  openconnect::ffi] Idle timeout is 180 minutes.
[2024-08-18T11:56:57Z WARN  openconnect::ffi] No MTU received. Calculated 1422 for ESP tunnel
[2024-08-18T11:56:57Z INFO  openconnect::ffi] POST https://xxx/ssl-vpn/hipreportcheck.esp
[2024-08-18T11:56:57Z WARN  openconnect::ffi] WARNING: Server asked us to submit HIP report with md5sum xxx. 
        VPN connectivity may be disabled or limited without HIP report submission.
        You need to provide a --csd-wrapper argument with the HIP report submission script.
[2024-08-18T11:56:57Z INFO  openconnect::ffi] ESP session established with server
[2024-08-18T11:56:57Z INFO  openconnect::ffi] ESP tunnel connected; exiting HTTPS mainloop.
[2024-08-18T11:56:58Z INFO  openconnect::ffi] Using vhost-net for tun acceleration, ring size 32
[2024-08-18T11:56:58Z INFO  openconnect::vpn] Connected to VPN, pipe_fd: 11
[2024-08-18T11:56:58Z INFO  gpclient::connect] Wrote PID 281078 to /var/run/gpclient.lock
```

**Pull request merged**
