### PR TITLE
README.md: add section for NixOS

### PR DESCRIPTION
**Pull request by jerith666**
NixOS support was added in https://github.com/NixOS/nixpkgs/pull/106465.

### CODE REVIEW

**Comment by yuezk** [comment]
Thanks.

**Comment by mulias** [comment]
A note for anyone looking at this in the next few weeks: 

`globalprotect-openconnect` is not yet available via the standard NixOS channels. You'll be able to tell when it's available on `unstable` because it should show up here https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&query=globalprotect

In the mean time, I was able to get it working in a more roundabout way, which should be good enough until the `staging` branch gets merged into `master`. I'm still learning a lot about nix, so if there's a better way to do this please share!

In the cli:
```
# I don't know if it's important to use unstable, but it's what I'm using. This might reduce build time?
nix-channel --add https://nixos.org/channels/nixos-unstable nixos 
# create a channel for a revision of staging that has the package we want
nix-channel --add https://github.com/NixOS/nixpkgs/archive/b7666646457ee97b8914a88c78e1ee202bb8e833.tar.gz globalprotect-staging-snapshot
# update
nix-channel --update
```

In `/etc/nixos/configuration.nix`
```
{ config, pkgs, ... }:
let
  globalprotect-openconnect = (import <globalprotect-staging-snapshot> {}).pkgs.globalprotect-openconnect;
in
{
  # here I tried to do
  #    imports = [ 
  #      ./hardware-configuration.nix
  #      <globalprotect-staging-snapshot/nixos/modules/services/networking/globalprotect-vpn.nix>
  #    ];
  # but I got the error "attribute 'globalprotect-openconnect' missing, at /nix/var/nix/profiles/per-user/root/channels/globalprotect-staging-snapshot/nixos/modules/services/networking/globalprotect-vpn.nix:9:10"
  # So instead I copied in the contents of the service, bellow
  imports = [ ./hardware-configuration.nix ];
 
  # Copy in the contents of the service we need, since importing isn't working
  services.dbus.packages = [ globalprotect-openconnect ];
  systemd.services.gpservice = {
  description = "GlobalProtect openconnect DBus service";
    serviceConfig = {
      Type="dbus";
      BusName="com.yuezk.qt.GPService";
      ExecStart="${globalprotect-openconnect}/bin/gpservice";
    };
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
  };
  
  ...
  
  environment.systemPackages = with pkgs; [
   globalprotect-openconnect
   my-other-packages
 ];
  ```
  
Finally, run `nixos-rebuild switch`. This took ~7 hours on my machine, presumably because of Qt5 stuff getting built from `staging`.

**Comment by jerith666** [comment]
Glad it's helpful!  :)

I may have been a bit premature with this PR since even after it lands in `nixos-unstable`, it won't be in a stable release until 21.11 (in November 2021, as the name implies).

That said, your approach looks about right to me.  I don't know how to avoid having to repeat the service definition in-line as you've done.  :-/

It's certainly fine to skip the first `nix-channel` command too, leaving the rest of the system on a stable channel.  (It won't affect build times much either way -- the caches that nixos pulls from are global, not per-channel.)

Another alternative is to clone https://github.com/NixOS/nixpkgs/, checkout the commit from my PR, and run `nixos-rebuild -I nixpkgs=/path/to/your/clone/of/nixpkgs`.  This would avoid the need to inline the service definition, but requires managing updates by hand, which you might not want to bite off.

**Comment by mulias** [comment]
Update: looks like it's made its way to `unstable`

**Pull request merged**
